Fix Empty Output on MacOS 26 (#65)
* Fix Empty Output on MacOS 26

* Update MacOS Detection

* Add Comments

* Restyled Fix Empty Output on MacOS 26 (#67)

* Restyled by shellharden

* Restyled by shfmt

---------

Co-authored-by: Restyled.io <commits@restyled.io>

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Restyled.io <commits@restyled.io>

diff --git a/lsusb b/lsusb
--- a/lsusb
+++ b/lsusb
@@ -1,22 +1,32 @@
 #!/usr/bin/env bash
 # lsusb (list USB devices) utility for macOS
 # Author: JLH, Sep 2013
-# Author: LanikSJ, Oct 2023
+# Author: LanikSJ, Oct 2023 - 2025
 #
 # Disclaimer: Usage info and functionality from lsusb under Linux
 
 # Turn on extended patterns
 shopt -s extglob
 
+# Determine the appropriate system_profiler data type based on macOS version
+major_version=$(sw_vers -productVersion 2>/dev/null | cut -d. -f1)
+if [ "$major_version" -ge 26 ] 2>/dev/null; then
+  host_type="SPUSBHostDataType"
+else
+  host_type="SPUSBDataType"
+fi
+
 verbose() {
-  system_profiler SPUSBDataType 2>/dev/null
+  # Get the full output of system_profiler
+  system_profiler "$host_type" 2>/dev/null
 
   # Restore the IFS and exit
   cleanup
 }
 
 version() {
-  echo "lsusb for macOS 1.1.3"
+  # Show version of program
+  echo "lsusb for macOS 1.1.4"
 
   # Restore the IFS and exit
   cleanup
@@ -26,7 +36,7 @@ help() {
   cat >&2 <<EOM
 $(usage)
 List USB devices
-  -v  Increase verbosity (show output of "system_profiler SPUSBDataType")
+  -v  Increase verbosity (show output of "system_profiler $host_type")
   -s  [[bus]:][devnum]
       Show only devices with specified device and/or
       bus numbers (in decimal)
@@ -39,8 +49,8 @@ List USB devices
   -h  Show usage and help
 EOM
 
-# Restore the IFS and exit
-cleanup
+  # Restore the IFS and exit
+  cleanup
 }
 
 usage() {
@@ -112,21 +122,21 @@ parse() {
     # The PID depends on the speed of the hub, which we deduce from the controller driver.
     PID=$(echo "$device" | grep "Controller Driver" | awk -F':' '{print $2}' | sed -e 's/0x//; s/^ *//g' -e 's/ *$//g; s/.*\(....\)$/\1/')
     case "$PID" in
-    OHCI)
-      PID="8005"
-      name="OHCI Root Hub Simulation"
-      speed="12M"
-      ;;
-    EHCI)
-      PID="8006"
-      name="EHCI Root Hub Simulation"
-      speed="480M"
-      ;;
-    XHCI)
-      PID="8007"
-      name="XHCI Root Hub USB 2.0 Simulation"
-      speed="5000M"
-      ;;
+      OHCI)
+        PID="8005"
+        name="OHCI Root Hub Simulation"
+        speed="12M"
+        ;;
+      EHCI)
+        PID="8006"
+        name="EHCI Root Hub Simulation"
+        speed="480M"
+        ;;
+      XHCI)
+        PID="8007"
+        name="XHCI Root Hub USB 2.0 Simulation"
+        speed="5000M"
+        ;;
     esac
   fi
 
@@ -236,7 +246,7 @@ setup() {
 cleanup() {
   IFS=$OIFS
   # shellcheck disable=SC2086
-  exit $exitcode
+  exit "$exitcode"
 }
 
 buildtreeline() {
@@ -254,9 +264,9 @@ buildtreeline() {
   if [ ${#spaces} -eq 0 ]; then
     spaces=" /:  "
   else
-    spaces="${spaces}|__ "
+    spaces="$spaces|__ "
   fi
-  treeline="${locationID}${spaces}Bus ""${bus_num}"".Dev ""${device_num}"": ""${name}"", ""${speed}"
+  treeline="$locationID${spaces}Bus ""$bus_num"".Dev ""$device_num"": ""$name"", ""$speed"
 }
 
 get_devices() {
@@ -272,29 +282,29 @@ tree() {
   setup
   treeflag="yes"
 
-  for device in $(get_devices); do
+  for device in "$(get_devices)"; do
     # Skip null device lines
     if [ "${#device}" != 1 ]; then
       parse
       buildtreeline
-      treedata="$treedata""${treeline}"$'\n'
+      treedata="$treedata""$treeline"$'\n'
     fi
   done
 
-  for device in $(get_buses); do
+  for device in "$(get_buses)"; do
     parse
     buildtreeline
-    treedata="${treedata}""${treeline}"$'\n'
+    treedata="$treedata""$treeline"$'\n'
   done
 
   # Strip off final \n.
-  treedata=$(echo "${treedata}" | awk '{ prev_line = line; line = $0; } NR > 1 { print prev_line; } END { ORS = ""; print line; }')
+  treedata=$(echo "$treedata" | awk '{ prev_line = line; line = $0; } NR > 1 { print prev_line; } END { ORS = ""; print line; }')
 
   # Sort by Location ID.
-  treedata=$(echo "${treedata}" | sort)
+  treedata=$(echo "$treedata" | sort)
 
   # Now strip off leading Location ID and print to stdout.
-  for line in $treedata; do
+  for line in "$treedata"; do
     echo -e "$line"
   done
 
@@ -305,25 +315,25 @@ tree() {
 # Parse options
 while getopts ":hvpd:s:Vt" opt; do
   case "$opt" in
-  h)
-    help
-    ;; # help
-  v)
-    verbose
-    ;; # verbose
-  t)
-    tree
-    ;; # tree
-  V)
-    version
-    ;;           # version
-  d) vid_pid=$OPTARG ;; # filter
-  s) bus_dev=$OPTARG ;; # filter
-  p) parens="yes" ;;  # formatter
-  *)
-    echo >&2 "lsusb: invalid option -- '$OPTARG'"
-    help
-    ;;
+    h)
+      help
+      ;; # help
+    v)
+      verbose
+      ;; # verbose
+    t)
+      tree
+      ;; # tree
+    V)
+      version
+      ;;                  # version
+    d) vid_pid=$OPTARG ;; # filter
+    s) bus_dev=$OPTARG ;; # filter
+    p) parens="yes" ;;    # formatter
+    *)
+      echo >&2 "lsusb: invalid option -- '$OPTARG'"
+      help
+      ;;
   esac
 done
 
@@ -349,7 +359,7 @@ setup
 
 # Iterate over each entry
 if [ -z "$get_devices" ]; then
-  for device in $(get_devices); do
+  for device in "$(get_devices)"; do
     if parse; then
       # Print the formatted entry
       echo "Bus ""$bus_num"" Device ""$device_num"": ID ""$VID"":""$PID"" ""$manufacturer"" ""$name"" ""$serial_str"
@@ -358,7 +368,7 @@ if [ -z "$get_devices" ]; then
 fi
 
 if [ -n "$get_buses" ]; then
-  for device in $(get_buses); do
+  for device in "$(get_buses)"; do
     if parse; then
       # Print the formatted entry
       echo "Buses:" && echo "Bus ""$bus_num"" Device ""$device_num"": ID ""$VID"":""$PID"" ""$manufacturer"" ""$name"" ""$serial_str"
